-- 1A. DISPLAY THE FIRST AND LAST NAMES OF ALL ACTORS FROM THE TABLE `ACTOR`

USE SAKILA;

SELECT FIRST_NAME,LAST_NAME 
FROM ACTOR;

-- 1B. DISPLAY THE FIRST AND LAST NAME OF EACH ACTOR IN A SINGLE COLUMN IN UPPER CASE LETTERS. 
-- NAME THE COLUMN `ACTOR NAME`. 

USE SAKILA;

SELECT UPPER(CONCAT(FIRST_NAME,' ',LAST_NAME)) AS `ACTOR NAME`
FROM ACTOR;