-- 2A. YOU NEED TO FIND THE ID NUMBER, FIRST NAME, AND LAST NAME OF AN ACTOR, 
-- OF WHOM YOU KNOW ONLY THE FIRST NAME, "JOE." 
-- WHAT IS ONE QUERY WOULD YOU USE TO OBTAIN THIS INFORMATION?	
USE SAKILA;

SELECT ACTOR_ID, FIRST_NAME, LAST_NAME
FROM ACTOR
WHERE FIRST_NAME = 'JOE';


-- 2B. FIND ALL ACTORS WHOSE LAST NAME CONTAIN THE LETTERS `GEN`:
USE SAKILA;

SELECT ACTOR_ID, FIRST_NAME, LAST_NAME
FROM ACTOR
WHERE LAST_NAME LIKE '%GEN%';


-- 2C. FIND ALL ACTORS WHOSE LAST NAMES CONTAIN THE LETTERS `LI`. 
-- THIS TIME, ORDER THE ROWS BY LAST NAME AND FIRST NAME, IN THAT ORDER:

USE SAKILA;

SELECT ACTOR_ID, FIRST_NAME, LAST_NAME
FROM ACTOR
WHERE LAST_NAME LIKE '%LI%'
ORDER BY LAST_NAME,FIRST_NAME;


-- 2D. USING `IN`, DISPLAY THE `COUNTRY_ID` AND `COUNTRY` COLUMNS OF THE FOLLOWING COUNTRIES: 
-- AFGHANISTAN, BANGLADESH, AND CHINA:

USE SAKILA;

SELECT COUNTRY_ID, COUNTRY
FROM COUNTRY
WHERE COUNTRY IN ('AFGHANISTAN', 'BANGLADESH','CHINA');