-- 4A. LIST THE LAST NAMES OF ACTORS, AS WELL AS HOW MANY ACTORS HAVE THAT LAST NAME.
USE SAKILA;
SELECT LAST_NAME, COUNT(ACTOR_ID) AS FREQ
FROM ACTOR
GROUP BY LAST_NAME;


-- 4B. LIST LAST NAMES OF ACTORS AND THE NUMBER OF ACTORS WHO HAVE THAT LAST NAME, 
-- BUT ONLY FOR NAMES THAT ARE SHARED BY AT LEAST TWO ACTORS

USE SAKILA;
SELECT LAST_NAME, COUNT(ACTOR_ID) AS FREQ
FROM ACTOR
GROUP BY LAST_NAME
HAVING FREQ > 2;
  	
-- 4C. OH, NO! THE ACTOR `HARPO WILLIAMS` WAS ACCIDENTALLY ENTERED IN THE `ACTOR` 
-- TABLE AS `GROUCHO WILLIAMS`, THE NAME OF HARPO'S SECOND COUSIN'S HUSBAND'S YOGA TEACHER. 
-- WRITE A QUERY TO FIX THE RECORD.

UPDATE ACTOR
SET  FIRST_NAME = 'HARPO'
WHERE FIRST_NAME = 'GROUCHO'  AND LAST_NAME = 'WILLIAMS';

-- 4D. PERHAPS WE WERE TOO HASTY IN CHANGING `GROUCHO` TO `HARPO`. 
-- IT TURNS OUT THAT `GROUCHO` WAS THE CORRECT NAME AFTER ALL! IN A SINGLE QUERY, 
-- IF THE FIRST NAME OF THE ACTOR IS CURRENTLY `HARPO`, CHANGE IT TO `GROUCHO`. 
-- OTHERWISE, CHANGE THE FIRST NAME TO `MUCHO GROUCHO`, AS THAT IS EXACTLY 
-- WHAT THE ACTOR WILL BE WITH THE GRIEVOUS ERROR. 
-- BE CAREFUL NOT TO CHANGE THE FIRST NAME OF EVERY ACTOR TO `MUCHO GROUCHO`, 
-- HOWEVER! (HINT: UPDATE THE RECORD USING A UNIQUE IDENTIFIER.)

-- SOLUTION 01(I AM GETTING AN ERROR!)
UPDATE ACTOR
SET FIRST_NAME = CASE
WHEN FIRST_NAME = 'HARPO' THEN 'GROUCHO' 
ELSE 'MUCHO GROUCHO' 
END WHERE ACTOR_ID IN 
(SELECT ACTOR_ID FROM ACTOR
WHERE FIRST_NAME = 'HARPO');

-- SOLUTION 02
UPDATE ACTOR 
SET FIRST_NAME= 'HARPO'
WHERE FIRST_NAME='GROUCHO' AND LAST_NAME='WILLIAMS';