-- 5A. YOU CANNOT LOCATE THE SCHEMA OF THE `ADDRESS` TABLE. 
-- WHICH QUERY WOULD YOU USE TO RE-CREATE IT?

-- FOR FORMATTED OUTPUT
DESCRIBE ADDRESS;

-- SQL STATEMENT THAT CAN BE USED TO CREATE A TABLE
SHOW CREATE TABLE  ADDRESS;